Update daily-commit-summary.yml

diff --git a/.github/workflows/daily-commit-summary.yml b/.github/workflows/daily-commit-summary.yml
--- a/.github/workflows/daily-commit-summary.yml
+++ b/.github/workflows/daily-commit-summary.yml
@@ -17,26 +17,43 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
-          # Obtener todos los repositorios de la organización
-          repos=$(curl -H "Authorization: token $GH_TOKEN" \
+          echo "Obteniendo la lista de repositorios de la organización..."
+          repos=$(curl -H "Authorization: token $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/orgs/Galvez-Gil-E-Commerce/repos | jq -r '.[].full_name')
+          https://api.github.com/orgs/YOUR_ORG/repos | jq -r '.[].full_name')
+          
+          if [ -z "$repos" ]; then
+            echo "No se encontraron repositorios o hubo un error al obtener los repositorios."
+            exit 1
+          fi
           
           commits=""
           
-          # Obtener los commits del día para cada repositorio
+          echo "Iterando sobre los repositorios para obtener los commits del día..."
           for repo in $repos; do
+            echo "Obteniendo commits para el repositorio $repo..."
             repo_commits=$(curl -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/$repo/commits?since=$(date -d '1 day ago' --utc +%Y-%m-%dT%H:%M:%SZ)&until=$(date --utc +%Y-%m-%dT%H:%M:%SZ)" \
             | jq -r '.[] | "* [\(.commit.message)](\(.html_url)) by \(.commit.author.name)"')
+            
+            if [ $? -ne 0 ]; then
+              echo "Error al obtener commits para el repositorio $repo."
+              exit 2
+            fi
             
             if [ -n "$repo_commits" ]; then
               commits="$commits\n\n### $repo\n$repo_commits"
             fi
           done
           
+          if [ -z "$commits" ]; then
+            echo "No se encontraron commits para el día."
+            commits="No se encontraron commits para el día."
+          fi
+          
           echo -e "$commits" > commits.md
+          echo "Commits guardados en commits.md"
 
       - name: Send email
         uses: dawidd6/action-send-mail@v2
